default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: cigar2_development

test:
  <<: *default
  database: cigar2_test

production:
  <<: *default
  database: cigar2_production
  ## username: cigar2
  ## password: <%= ENV['CIGAR2_DATABASE_PASSWORD'] %>
